### ISSUE TITLE
job_add_data adds no data

### ISSUE THREAD

**Issue by jblumenau** [cloudyr/crowdflower#14]
Hi all,

Just started playing with this -- looks great! However, I tried following the vignette, and found that `job_add_data` fails to add data to my job.

Code:

    f1 <- system.file("templates", "instructions1.html", package = "crowdflower")

    f2 <- system.file("templates", "cml1.xml", package = "crowdflower")
   
     j1 <- job_create(title = "My job", 
                 instructions = readChar(f1, nchars = 1e8L),
                 cml = readChar(f2, nchars = 1e8L))

    d <- data.frame(content = c("Hello","Goodbye","World"))

    job_add_data(id = j1, data = d)

No error message coming from the function, just nothing appearing on the crowdflower  Your Jobs page. Also doesn't seem to work if I pass a file to the `data` argument.

Thanks!

**Comment by leeper** [comment]
Thanks for reporting this, @jblumenau. It should now be fixed.
